apiVersion: mesh.openkcm.io/v1alpha1
kind: CryptoEdgeDeployment
metadata:
  # Name doubles as the namespace in the target cluster
  name: echo-server-edge01
  namespace: default
spec:
  # Inline account information
  account:
    name: dev-account
  # Inline region information
  region:
    name: edge01
